### ISSUE TITLE
Questions…

### ISSUE THREAD

**Issue by rchrdnsh** [srmullen/sveltekit-stripe#1]
Soooooooooo,

This this awesome :-)

Curious what it would like like in vanilla js, as I don't really know much ts. Is it important to ts to keep this kind of stuff..."safe"...I guess?

Also, would it be a tough task to augment this to work with stripe elements for a custom checkout flow? I understand that a checkout form would have to be created, but would the other stuff, like generating products and all the endpoints and the scripts stuff translate relatively easy?

Anyway, super awesome work on this :-)

**Comment by srmullen** [comment]
Hey! Thanks for the kind words.

You could strip out all the ts and it would be just as "safe" at runtime as it currently is. TS helps you catch type errors at compile-time, so you'd be more likely to introduce those errors into your codebase if you started developing more on top of this. But if you're already used to writing js there's nothing new there. It wouldn't take much effort to convert this repo to plain js.

Creating a custom checkout for demonstration purposes wouldn't be too difficult. It gets harder to make something that works as well as the Stripe Checkout page though. It handles a lot of things out of the box. Everything else should translate pretty easily following the patterns here.
