### ISSUE TITLE
plansData.json in .gitignore

### ISSUE THREAD

**Issue by caseyplummer4haliontech** [srmullen/sveltekit-stripe#5]
Just curious why plansData.json is present in the .gitignore file? Is this sensitive data? Or does it vary by environment (Stripe test versus production). Seems like I have to commit and deploy it in order for the non-local environment to work. Thanks.

**Comment by srmullen** [comment]
The reason I have the file in .gitignore is that this repo is presented as a template/demo, so I  don't want it to contain any information specific to my stripe account. It's not sensitive information though and you could push it to Github.

The json file was really just a way to store/persist this information without needing a database, so this repo would be easier to get working locally. You can store and access the data in whatever format best suits the rest of your setup though.

I think it's a good point to call out. I'll add something to the readme about this. Thanks for pointing it out!

**Comment by orefalo** [comment]
great reasoning - can't disagree.
now this ticket shall be closed
